import { Router, type IRouter } from "express";
import healthRouter from "./health";
import vehiclesRouter from "./vehicles";
import alertsRouter from "./alerts";
import documentsRouter from "./documents";
import publicRouter from "./public";
import usersRouter from "./users";
import adminRouter from "./admin";
import sosProfileRouter from "./sosProfile";
import accidentReportsRouter from "./accidentReports";
import lostItemsRouter from "./lostItems";
import paymentRouter from "./payment";
import qrSettingsRouter from "./qr-settings";
import stickerOrdersRouter from "./stickerOrders";
import contactRouter from "./contact";
import legalRouter from "./legal";
import faqsRouter from "./faqs";
import testimonialsRouter from "./testimonials";
import supportTicketsRouter from "./supportTickets";
import notificationsRouter from "./notifications";
import storageRouter from "./storage";
import documentExpiryRouter from "./documentExpiry";
import billingRouter from "./billing";

const router: IRouter = Router();

router.use(healthRouter);
router.use(vehiclesRouter);
router.use(alertsRouter);
router.use(documentsRouter);
router.use(publicRouter);
router.use(usersRouter);
router.use(adminRouter);
router.use(sosProfileRouter);
router.use(accidentReportsRouter);
router.use(lostItemsRouter);
router.use(paymentRouter);
router.use(qrSettingsRouter);
router.use(stickerOrdersRouter);
router.use(contactRouter);
router.use(legalRouter);
router.use(faqsRouter);
router.use(testimonialsRouter);
router.use(supportTicketsRouter);
router.use(notificationsRouter);
router.use(storageRouter);
router.use(documentExpiryRouter);
router.use(billingRouter);

export default router;
